### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by stereobooster** [tex0l/astro-pintora#1]
Hey 👋 .

I was thinking to implement similar package. But you were faster. Some ideas to improve package:

- [xxhash](https://www.npmjs.com/package/@node-rs/xxhash) is faster hashing algorithm
- For `cache` instead of `{}` it would be better to use some kind of LRU. For example, [flru](https://github.com/lukeed/flru). But I didn't bench-marked it, so there can be better alternatives
- maybe put link back to the repository in `package.json`. I had to google, to find the source code.

**Comment by tex0l** [comment]
Hi @stereobooster,
Thank you for your contribution! Sorry I was unresponsive these past few weeks.

I added the homepage in the repository, I'll update the peer dependency for astro 4.

As for xxhash and an LRU, I agree in principle that it'd be much faster to use these rather than a basic SHA256 and an object, however, are these two things really a bottleneck?

Are you experiencing slowdowns in practice? If so, I'd be happy to optimize, otherwise I'd rather keep it as simple as possible with as few dependencies as possible.

**Comment by stereobooster** [comment]
> I added the homepage in the repository, I'll update the peer dependency for astro 4.

👍 

> Are you experiencing slowdowns in practice? 

Not really. Rather wanted to share some ideas with you. You can close ticket
